# Secara default, MongoDB itu tidak perlu ?create database? secara manual seperti di PostgreSQL/MySQL.
# Database akan otomatis dibuat saat pertama kali kamu insert data.
# Kalau kamu connect ke DB yang belum ada ? tidak error
# DB baru benar-benar dibuat saat: ada collection dibuat, atau ada insert data pertama

spring.application.name=springboot-mongodb

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://${MONGO_USERNAME:appuser}:${MONGO_PASSWORD:apppass}@${MONGO_HOST:localhost}:${MONGO_PORT:37018}/${MONGO_DB:mydbmongo}?authSource=admin
