services:
  mongo:
    image: mongo:8.0
    restart: always
    ports:
      - 37018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: appuser
      MONGO_INITDB_ROOT_PASSWORD: apppass
      MONGO_INITDB_DATABASE: mydbmongo   # 👈 nama database awal
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://appuser:apppass@mongo:27017/mydbmongo?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass

  springboot:
    image: springboot-mongodb:v1.0
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - MONGO_USERNAME=appuser
      - MONGO_PASSWORD=apppass
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=mydbmongo

volumes:
  mongo-data:
